name: 'Pull Request'

on:
    pull_request:
    push:
        branches:
            - main

env:
    CHANNEL_ID: C09Q36G9HMX # sandbox

jobs:
  alert-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send message the Slack channel
        uses: slack-notification.yml
        id: slack_thread
        with:
          channel_id: ${{ env.CHANNEL_ID }}
          message: >
            [ <${{ github.event.pull_request.html_url }}|PR Review> ] ${{ github.event.repository.name }} - #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}
          thread_message: "Please review the above pull request."