name: 'Slack Notification'

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  alert-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send message the Slack channel
        uses: slackapi/slack-github-action@v2.1.1
        with:
            method: chat.postMessage
            token: ${{ secrets.SLACK_OAUTH_TOKEN }}
            payload: |
              channel: "#sandbox"
              text: "Message content"