name: 'Slack Notification'

on:
  workflow_dispatch:

jobs:
  alert-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version-file: .nvmrc
      - name: Send message to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_OAUTH_TOKEN }}
        with:
          channel-id: C09Q36G9HMX #sandbox
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Message one"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Message 2"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Message 3"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "<Message 4>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Workflow Run>"
                    }
                    
                  ]
                }
              ],
              "unfurl_links": false,
              "unfurl_media": false
            }