name: 'Slack Notification'

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  alert-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send message the Slack channel
        uses: slackapi/slack-github-action@v2
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_OAUTH_TOKEN }}
          ## CHANNEL_ID: C09Q36G9HMX # Sandbox
          CHANNEL_ID: "D09H54ABJMQ" # Direct Message to Tim
        with:
            errors: true
            method: chat.postMessage
            token: ${{ env.SLACK_BOT_TOKEN }}
            payload: |
              channel: "${{ env.CHANNEL_ID }}"
              text: "[ <${{ github.event.pull_request.url }}|SHOW PR!> ] ${{ github.event.repository.name }} - #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
